name: Update esp-idf
on:
  push:
    paths:
      - 'esp-idf_cpp/**'
  workflow_dispatch:

jobs:
  update_repo1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: segin-GH/esp-idf
          path: repo1
      - name: Update submodule
        run: |
          cd repo1
          git submodule update --remote
      - name: Commit and push changes
        run: |
          cd repo1
          git config --global user.email "segin.bytes@gmail.com"
          git config --global user.name "segin-GH"
          git add .
          git commit -m "Updated submodule"
          git push origin master
